// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Match Next.js precedence: .env.local overrides .env. dotenv won't re-set
// keys that are already defined, so loading .env.local first is what we want.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
loadEnv();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
